version: '3.5'

services:
  postgres:
    container_name: postgres_db_container
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123qwe
      POSTGRES_DB: test_django_db
      PGDATA: /postgres/data/
      POSTGRES_INITDB_ARGS: "-A md5"

    ports:
      - "5433:5432"
    restart: always

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: test@test.com
      PGADMIN_DEFAULT_PASSWORD: 123qwe
    ports:
        - "5050:80"