# Generated by Django 4.1.5 on 2023-02-10 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smoke_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countersbyeffect',
            name='counters',
        ),
    ]
